package main

// generated from LMU SharedMemoryInterface layout (via lmu-pitwall, MIT)
const W_SIZE = 260
const W_mSuspensionDeflection = 0        // f64
const W_mRideHeight = 8                  // f64
const W_mSuspForce = 16                  // f64
const W_mBrakeTemp = 24                  // f64
const W_mBrakePressure = 32              // f64
const W_mRotation = 40                   // f64
const W_mLateralPatchVel = 48            // f64
const W_mLongitudinalPatchVel = 56       // f64
const W_mLateralGroundVel = 64           // f64
const W_mLongitudinalGroundVel = 72      // f64
const W_mCamber = 80                     // f64
const W_mLateralForce = 88               // f64
const W_mLongitudinalForce = 96          // f64
const W_mTireLoad = 104                  // f64
const W_mGripFract = 112                 // f64
const W_mPressure = 120                  // f64
const W_mTemperature = 128               // [f64; 3]
const W_mWear = 152                      // f64
const W_mTerrainName = 160               // [u8; 16]
const W_mSurfaceType = 176               // u8
const W_mFlat = 177                      // u8
const W_mDetached = 178                  // u8
const W_mStaticUndeflectedRadius = 179   // u8
const W_mVerticalTireDeflection = 180    // f64
const W_mWheelYLocation = 188            // f64
const W_mToe = 196                       // f64
const W_mTireCarcassTemperature = 204    // f64
const W_mTireInnerLayerTemperature = 212 // [f64; 3]
const W_mOptimalTemp = 236               // f32
const W_mCompoundIndex = 240             // u8
const W_mCompoundType = 241              // u8
const W_mExpansion = 242                 // [u8; 18]
const T_SIZE = 1888
const T_mID = 0                              // i32
const T_mDeltaTime = 4                       // f64
const T_mElapsedTime = 12                    // f64
const T_mLapNumber = 20                      // i32
const T_mLapStartET = 24                     // f64
const T_mVehicleName = 32                    // [u8; 64]
const T_mTrackName = 96                      // [u8; 64]
const T_mPos = 160                           // rF2Vec3
const T_mLocalVel = 184                      // rF2Vec3
const T_mLocalAccel = 208                    // rF2Vec3
const T_mOri = 232                           // [rF2Vec3; 3]
const T_mLocalRot = 304                      // rF2Vec3
const T_mLocalRotAccel = 328                 // rF2Vec3
const T_mGear = 352                          // i32
const T_mEngineRPM = 356                     // f64
const T_mEngineWaterTemp = 364               // f64
const T_mEngineOilTemp = 372                 // f64
const T_mClutchRPM = 380                     // f64
const T_mUnfilteredThrottle = 388            // f64
const T_mUnfilteredBrake = 396               // f64
const T_mUnfilteredSteering = 404            // f64
const T_mUnfilteredClutch = 412              // f64
const T_mFilteredThrottle = 420              // f64
const T_mFilteredBrake = 428                 // f64
const T_mFilteredSteering = 436              // f64
const T_mFilteredClutch = 444                // f64
const T_mSteeringShaftTorque = 452           // f64
const T_mFront3rdDeflection = 460            // f64
const T_mRear3rdDeflection = 468             // f64
const T_mFrontWingHeight = 476               // f64
const T_mFrontRideHeight = 484               // f64
const T_mRearRideHeight = 492                // f64
const T_mDrag = 500                          // f64
const T_mFrontDownforce = 508                // f64
const T_mRearDownforce = 516                 // f64
const T_mFuel = 524                          // f64
const T_mEngineMaxRPM = 532                  // f64
const T_mScheduledStops = 540                // u8
const T_mOverheating = 541                   // u8
const T_mDetached = 542                      // u8
const T_mHeadlights = 543                    // u8
const T_mDentSeverity = 544                  // [u8; 8]
const T_mLastImpactET = 552                  // f64
const T_mLastImpactMagnitude = 560           // f64
const T_mLastImpactPos = 568                 // rF2Vec3
const T_mEngineTorque = 592                  // f64
const T_mCurrentSector = 600                 // i32
const T_mSpeedLimiter = 604                  // u8
const T_mMaxGears = 605                      // u8
const T_mFrontTireCompoundIndex = 606        // u8
const T_mRearTireCompoundIndex = 607         // u8
const T_mFuelCapacity = 608                  // f64
const T_mFrontFlapActivated = 616            // u8
const T_mRearFlapActivated = 617             // u8
const T_mRearFlapLegalStatus = 618           // u8
const T_mIgnitionStarter = 619               // u8
const T_mFrontTireCompoundName = 620         // [u8; 18]
const T_mRearTireCompoundName = 638          // [u8; 18]
const T_mSpeedLimiterAvailable = 656         // u8
const T_mAntiStallActivated = 657            // u8
const T_mUnused = 658                        // [u8; 2]
const T_mVisualSteeringWheelRange = 660      // f32
const T_mRearBrakeBias = 664                 // f64
const T_mTurboBoostPressure = 672            // f64
const T_mPhysicsToGraphicsOffset = 680       // [f32; 3]
const T_mPhysicalSteeringWheelRange = 692    // f32
const T_mDeltaBest = 696                     // f64
const T_mBatteryChargeFraction = 704         // f64
const T_mElectricBoostMotorTorque = 712      // f64
const T_mElectricBoostMotorRPM = 720         // f64
const T_mElectricBoostMotorTemperature = 728 // f64
const T_mElectricBoostWaterTemperature = 736 // f64
const T_mElectricBoostMotorState = 744       // u8
const T_mLapInvalidated = 745                // u8
const T_mABSActive = 746                     // u8
const T_mTCActive = 747                      // u8
const T_mSpeedLimiterActive = 748            // u8
const T_mWiperState = 749                    // u8
const T_mTC = 750                            // u8
const T_mTCMax = 751                         // u8
const T_mTCSlip = 752                        // u8
const T_mTCSlipMax = 753                     // u8
const T_mTCCut = 754                         // u8
const T_mTCCutMax = 755                      // u8
const T_mABS = 756                           // u8
const T_mABSMax = 757                        // u8
const T_mMotorMap = 758                      // u8
const T_mMotorMapMax = 759                   // u8
const T_mMigration = 760                     // u8
const T_mMigrationMax = 761                  // u8
const T_mFrontAntiSway = 762                 // u8
const T_mFrontAntiSwayMax = 763              // u8
const T_mRearAntiSway = 764                  // u8
const T_mRearAntiSwayMax = 765               // u8
const T_mLiftAndCoastProgress = 766          // u8
const T_mTrackLimitsSteps = 767              // u8
const T_mRegen = 768                         // f32
const T_mSoC = 772                           // f32
const T_mVirtualEnergy = 776                 // f32
const T_mTimeGapCarAhead = 780               // f32
const T_mTimeGapCarBehind = 784              // f32
const T_mTimeGapPlaceAhead = 788             // f32
const T_mTimeGapPlaceBehind = 792            // f32
const T_mVehicleModel = 796                  // [u8; 30]
const T_mVehicleClassEnum = 826              // u8
const T_mVehicleChampionshipEnum = 827       // u8
const T_mExpansion = 828                     // [u8; 20]
const T_mWheels = 848                        // [rF2Wheel; 4]
const V_SIZE = 584
const V_mID = 0                 // i32
const V_mDriverName = 4         // [u8; 32]
const V_mVehicleName = 36       // [u8; 64]
const V_mTotalLaps = 100        // i16
const V_mSector = 102           // i8
const V_mFinishStatus = 103     // i8
const V_mLapDist = 104          // f64
const V_mPathLateral = 112      // f64
const V_mTrackEdge = 120        // f64
const V_mBestSector1 = 128      // f64
const V_mBestSector2 = 136      // f64
const V_mBestLapTime = 144      // f64
const V_mLastSector1 = 152      // f64
const V_mLastSector2 = 160      // f64
const V_mLastLapTime = 168      // f64
const V_mCurSector1 = 176       // f64
const V_mCurSector2 = 184       // f64
const V_mNumPitstops = 192      // i16
const V_mNumPenalties = 194     // i16
const V_mIsPlayer = 196         // u8
const V_mControl = 197          // i8
const V_mInPits = 198           // u8
const V_mPlace = 199            // u8
const V_mVehicleClass = 200     // [u8; 32]
const V_mTimeBehindNext = 232   // f64
const V_mLapsBehindNext = 240   // i32
const V_mTimeBehindLeader = 244 // f64
const V_mLapsBehindLeader = 252 // i32
const V_mLapStartET = 256       // f64
const V_mPos = 264              // rF2Vec3
const V_mLocalVel = 288         // rF2Vec3
const V_mLocalAccel = 312       // rF2Vec3
const V_mOri = 336              // [rF2Vec3; 3]
const V_mLocalRot = 408         // rF2Vec3
const V_mLocalRotAccel = 432    // rF2Vec3
const V_mHeadlights = 456       // u8
const V_mPitState = 457         // u8
const V_mServerScored = 458     // u8
const V_mIndividualPhase = 459  // u8
const V_mQualification = 460    // i32
const V_mTimeIntoLap = 464      // f64
const V_mEstimatedLapTime = 472 // f64
const V_mPitGroup = 480         // [u8; 24]
const V_mFlag = 504             // u8
const V_mUnderYellow = 505      // u8
const V_mCountLapFlag = 506     // u8
const V_mInGarageStall = 507    // u8
const V_mUpgradePack = 508      // [u8; 16]
const V_mPitLapDist = 524       // f32
const V_mBestLapSector1 = 528   // f32
const V_mBestLapSector2 = 532   // f32
const V_mExpansion = 536        // [u8; 48]
const I_SIZE = 548
const I_mTrackName = 0                    // [u8; 64]
const I_mSession = 64                     // i32
const I_mCurrentET = 68                   // f64
const I_mEndET = 76                       // f64
const I_mMaxLaps = 84                     // i32
const I_mLapDist = 88                     // f64
const I_mPointer1 = 96                    // [u8; 8]
const I_mNumVehicles = 104                // i32
const I_mGamePhase = 108                  // u8
const I_mYellowFlagState = 109            // i8
const I_mSectorFlag = 110                 // [i8; 3]
const I_mStartLight = 113                 // u8
const I_mNumRedLights = 114               // u8
const I_mInRealtime = 115                 // u8
const I_mPlayerName = 116                 // [u8; 32]
const I_mPlrFileName = 148                // [u8; 64]
const I_mDarkCloud = 212                  // f64
const I_mRaining = 220                    // f64
const I_mAmbientTemp = 228                // f64
const I_mTrackTemp = 236                  // f64
const I_mWind = 244                       // rF2Vec3
const I_mMinPathWetness = 268             // f64
const I_mMaxPathWetness = 276             // f64
const I_mGameMode = 284                   // u8
const I_mIsPasswordProtected = 285        // u8
const I_mServerPort = 286                 // u16
const I_mServerPublicIP = 288             // u32
const I_mMaxPlayers = 292                 // i32
const I_mServerName = 296                 // [u8; 32]
const I_mStartET = 328                    // f32
const I_mAvgPathWetness = 332             // f64
const I_mSessionTimeRemaining = 340       // f32
const I_mTimeOfDay = 344                  // f32
const I_mIsFixedSetup = 348               // u8
const I_mTrackGripLevel = 349             // u8
const I_mCloudCoverage = 350              // u8
const I_mTrackLimitsStepsPerPenalty = 351 // u8
const I_mTrackLimitsStepsPerPoint = 352   // u8
const I_mExpansion = 353                  // [u8; 187]
const I_mPointer2 = 540                   // [u8; 8]
